version: "3.9"
services:
  openfisca:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    command: make serve-local
    user: user:user
    ports:
      - 50000:50000
    networks:
      - openfisca
  dashboard:
    build:
      context: ./dashboard
      dockerfile: ./Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    command: npm run dev
    user: user:user
    ports:
      - 30000:30000
    networks:
      - openfisca

networks:
  openfisca:
    name: openfisca
