version: "3.9"
services:
  openfisca:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "make serve-local"
    user: user:user
    ports:
      - 50000:50000
    networks:
      - openfisca
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    command: npm run dev
    user: user:user
    ports:
      - 30000:30000
    networks:
      - openfisca

networks:
  openfisca:
    name: openfisca
